config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :interactions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
      #root 'home#index'
      root 'interactions#index'
      get 'home/about'
      
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/interaction.rb
class Interaction < ApplicationRecord
    
    belongs_to :user
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    
    has_many :interactions
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
    
  def about
  end
    
end

app/controllers/interactions_controller.rb
class InteractionsController < ApplicationController
  before_action :set_interaction, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /interactions
  # GET /interactions.json
  def index
    @interactions = Interaction.all
  end

  # GET /interactions/1
  # GET /interactions/1.json
  def show
  end

  # GET /interactions/new
  def new
    #@interaction = Interaction.new
    @interaction = current_user.interactions.build
  end

  # GET /interactions/1/edit
  def edit
  end

  # POST /interactions
  # POST /interactions.json
  def create
    #@interaction = Interaction.new(interaction_params)
    @interaction = current_user.interactions.build(interaction_params)
    respond_to do |format|
      if @interaction.save
        format.html { redirect_to @interaction, notice: 'Interaction was successfully created.' }
        format.json { render :show, status: :created, location: @interaction }
      else
        format.html { render :new }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /interactions/1
  # PATCH/PUT /interactions/1.json
  def update
    respond_to do |format|
      if @interaction.update(interaction_params)
        format.html { redirect_to @interaction, notice: 'Interaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @interaction }
      else
        format.html { render :edit }
        format.json { render json: @interaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interactions/1
  # DELETE /interactions/1.json
  def destroy
    @interaction.destroy
    respond_to do |format|
      format.html { redirect_to interactions_url, notice: 'Interaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user
     @interaction = current_user.interactions.find_by(id: params[:id])
     redirect_to interactions_path, notice: "Not Authorized to Edit This Interaction" if @interaction.nil?
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interaction
      @interaction = Interaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def interaction_params
      params.require(:interaction).permit(:first_name, :last_name, :date, :relationship, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/interactions_helper.rb
module InteractionsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  
  <%= link_to 'RubyApp', root_path, class:"navbar-brand"%>  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
    <%= link_to 'About', home_about_path, class:"nav-link" %>
      </li>
    

        
    <% if user_signed_in? %>
        
        <li class="nav-item">
    <%= link_to 'New Entry', new_interaction_path, class:"nav-link" %>
      </li> 
        
        <li class="nav-item">
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
      </li>   
        
        <li class="nav-item">
    <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
      </li>   
    
    <% else %>
        <li class="nav-item">
    <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
      </li>    
 
        <li class="nav-item">
    <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
      </li>   
    <% end %>

        

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>      
            
</nav>

app/views/home/about.html.erb
<h1> About Me.... </h1>

app/views/home/index.html.erb
<h1>Hello World</h1>
Ruby Page

app/views/interactions/_form.html.erb
<%= form_with(model: interaction) do |form| %>
  <% if interaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(interaction.errors.count, "error") %> prohibited this interaction from being saved:</h2>

      <ul>
        <% interaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
  <% end %>


<div class="card">
  <div class="card-header">
<h4>Enter Below</h4>
    </div>
  <div class="card-body">
  <div class="field form-group">
    <% form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <% form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name"  %>
  </div>

  <div class="field form-group">
    <% form.label :relationship %>
    <%= form.text_field :relationship, class:"form-control", placeholder:"Relationship"  %>
  </div>

  <div class="field form-group">
    <%= form.label :date %>
    <%= form.date_select :date%>
  </div>

 <div class="field form-group">
    <%= form.number_field :user_id, id: :interaction_user_id, class:"form-control", value:current_user.id, type: :hidden%>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-success'%>
  </div>
<% end %>


 </div>
</div>

app/views/interactions/edit.html.erb
<h1>Editing Interaction</h1>

<%= render 'form', interaction: @interaction %>
<br>
<%= link_to 'Show', @interaction, class:"btn btn-info" %>
<%= link_to 'Delete', @interaction, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>

app/views/interactions/index.html.erb
<% if user_signed_in? %>

<h1>Interactions <%= link_to 'New Interaction', new_interaction_path, class:"btn btn-success" %> </h1> 

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <th>Date</th>
      <th>Relationship</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @interactions.each do |interaction| %>
      <% if interaction.user == current_user %>
      <tr>
        <td><%= link_to interaction.first_name + " " + interaction.last_name, interaction %></td>
        <td><%= interaction.date %></td>
        <td><%= interaction.relationship %></td>
        <td><%= link_to 'Delete', interaction, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-outline-danger btn-sm" %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%else %>
<h1>Hello World</h1>
Ruby Page Dude

<%end%>

app/views/interactions/new.html.erb
<h1>New Interaction</h1>

<%= render 'form', interaction: @interaction %>
<br>
<%= link_to 'Back', interactions_path, class:"btn btn-info" %>

app/views/interactions/show.html.erb
<div class="jumbotron">
  <h1 class="display-4">  <%= @interaction.first_name %> <%= @interaction.last_name %>
 </h1>
  <p class="lead">Interaction Date:   <%= @interaction.date %>
</p>
  <hr class="my-4">
  <p>Relationship:   <%= @interaction.relationship %>
</p>
<%= link_to 'Edit', edit_interaction_path(@interaction), class:"btn btn-info" %>
<%= link_to 'Home', interactions_path, class:"btn btn-info" %>
<%= link_to 'Delete', interactions_path, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
        <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Rubyapp</title>
      
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
    <% if notice %>
    <br>
    <%= render 'layouts/alerts' %>  
    <% end %>
        <br/>
    <%= yield %>
      </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <!-- Option 2: jQuery, Popper.js, and Bootstrap JS
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    -->
  </body>
</html>